name: jenkins_${JENKINS_VERSION}
version: "3"
services:
  jenkins-docker: 
    image: docker:${DOCKER_VERSION}
    container_name: jenkins-docker_${DOCKER_VERSION}
    privileged: true
    restart: unless-stopped
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/cert
      - TZ=${TIME_ZONE}
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-var:/var/lib/docker
    ports:
      - 2376:2376
    command: --storage-driver=overlay2
    deploy:
      resources:
        limits:
          memory: 4gb
        reservations:
          memory: 2gb
  jenkins-blueocean:
    image: jenkins-blueocean:${JENKINS_VERSION}
    container_name: jenkins-blueocean_${JENKINS_VERSION}
    depends_on:
      - jenkins-docker
      - jenkins-agent
    build:
      dockerfile: dockerfile
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
    restart: unless-stopped
    networks:
      - jenkins
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=0
      - TZ=${TIME_ZONE}
    ports:
      - "8080:8080"
      - "50000:50000" 
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    deploy:
      resources:
        limits:
          memory: 4gb
        reservations:
          memory: 2gb
  jenkins-agent:
    image: jenkins/ssh-agent:${AGENT_VERSION}
    container_name: jenkins-agent_${AGENT_VERSION}
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_PUBKEY}
      - TZ=${TIME_ZONE}
    restart: unless-stopped
    networks:
      - jenkins
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "2222:22"
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-agent-dot:/home/jenkins/.jenkins
      - jenkins-agent-home:/home/jenkins/agent
      - jenkins-agent-run:/run
      - jenkins-agent-tmp:/tmp
      - jenkins-agent-var:/var/run
    deploy:
      resources:
        limits:
          memory: 4gb
        reservations:
          memory: 2gb
networks:
  jenkins:
    name: jenkins
volumes:
  jenkins-docker-certs:
    name: jenkins_certs
  jenkins-docker-var:
    name: jenkins-docker-var
  jenkins-data:
    name: jenkins-blueocean_data
  jenkins-agent-dot:
    name: jenkins-agent-dot
  jenkins-agent-home:
    name: jenkins-agent-home
  jenkins-agent-run:
    name: jenkins-agent-run
  jenkins-agent-tmp:
    name: jenkins-agent-tmp
  jenkins-agent-var:
    name: jenkins-agent-var