name: jenkins_${JENKINS_VERSION}
version: "3"
services:
  jenkins-docker: 
    image: docker:${DOCKER_VERSION}
    container_name: jenkins-docker_${DOCKER_VERSION}
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/cert
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
    command: --storage-driver=overlay2
  jenkins-blueocean:
    image: jenkins-blueocean:${JENKINS_VERSION}
    container_name: jenkins-blueocean_${JENKINS_VERSION}
    depends_on:
      - jenkins-docker
      - jenkins-agent
    build:
      dockerfile: dockerfile
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
    restart: on-failure
    networks:
      - jenkins
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000" 
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
  jenkins-agent:
    image: jenkins/ssh-agent:${AGENT_VERSION}
    container_name: jenkins-agent_${JENKINS_VERSION}
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_PUBKEY}
    networks:
      - jenkins
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "2222:22"
    volumes:
      - agent-data:/home/jenkins
      - jenkins-docker-certs:/certs/client
networks:
  jenkins:
    name: jenkins
volumes:
  jenkins-docker-certs:
    name: jenkins_certs
  jenkins-data:
    name: jenkins-blueocean_data
  agent-data:
    name: jenkins-agent_data